# Habilitar o console visual do banco H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações de conexão (banco em memória)
spring.datasource.url=jdbc:h2:mem:vacinadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pede pro Hibernate criar as tabelas automaticamente baseado nas nossas classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true